import { WorkflowStep } from '../../types/robot.types'

/**
 * Helper to generate code execution logic for a single step.
 * Shared by both generateLua (single-file output) and generateSingleStepLua (multi-file output).
 */
function generateStepCode(step: WorkflowStep, d: (n: any, decimals?: number) => string): string {
  let code = ''
  switch (step.type) {
    case 'MoveJ':
      if (step.jointAngles) {
        const [j1, j2, j3, j4, j5, j6] = step.jointAngles
        // Format: MoveJ({j1..j6}, tool, user, vel, acc, blendT, blendR)
        code += `MoveJ({${d(j1)}, ${d(j2)}, ${d(j3)}, ${d(j4)}, ${d(j5)}, ${d(j6)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))`
      } else {
        code += `-- Lỗi: Thiếu thông số góc khớp cho MoveJ`
      }
      break

    case 'MoveL':
      if (step.tcpPose) {
        const { x, y, z, rx, ry, rz } = step.tcpPose
        // Format: MoveL({x, y, z, rx, ry, rz}, tool, user, vel, acc, blendT, blendR)
        code += `MoveL({${d(x)}, ${d(y)}, ${d(z)}, ${d(rx)}, ${d(ry)}, ${d(rz)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))`
      } else {
        code += `-- Lỗi: Thiếu thông số TCP cho MoveL`
      }
      break

    case 'RotateJoint':
      if (step.jointAngles) {
        const [j1, j2, j3, j4, j5, j6] = step.jointAngles
        code += `MoveJ({${d(j1)}, ${d(j2)}, ${d(j3)}, ${d(j4)}, ${d(j5)}, ${d(j6)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))`
      } else {
        code += `-- Lỗi: Chưa giải được góc khớp cho RotateJoint`
      }
      break

    case 'MoveTCP':
      if (step.tcpPose) {
        const { x, y, z, rx, ry, rz } = step.tcpPose
        code += `MoveL({${d(x)}, ${d(y)}, ${d(z)}, ${d(rx)}, ${d(ry)}, ${d(rz)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))`
      } else {
        code += `-- Lỗi: Chưa giải được tọa độ TCP cho MoveTCP`
      }
      break

    case 'SetDO': {
      const doIdx = step.doIndex !== undefined ? step.doIndex : 1
      const doVal = step.doValue !== undefined ? step.doValue : 1
      const doType = step.doType || 'cabinet'
      if (doType === 'tool') {
        // Format: SetToolDO(id, status, smooth, block)
        code += `SetToolDO(${doIdx}, ${doVal}, 0, 0)`
      } else {
        // Format: SetDO(index, status, block)
        code += `SetDO(${doIdx}, ${doVal}, 0)`
      }
      break
    }

    case 'WaitMs': {
      const delay = step.delayMs !== undefined ? step.delayMs : 1000
      // Format: WaitMs(ms)
      code += `WaitMs(${delay})`
      break
    }

    case 'GripperOpen':
      code += `-- Điều khiển mở kẹp tay gắp\n`
      code += `SetDO(1, 0, 0)\n`
      code += `WaitMs(500)`
      break

    case 'GripperClose':
      code += `-- Điều khiển đóng kẹp tay gắp\n`
      code += `SetDO(1, 1, 0)\n`
      code += `WaitMs(500)`
      break

    case 'TriggerDevice': {
      const objName = step.targetObjectName || 'Thiết bị'
      const objId = step.targetObjectId || 'unknown_id'
      const cmd = step.deviceCommand || 'ON'
      const val = step.deviceValue !== undefined ? step.deviceValue : 1
      code += `-- [Kích hoạt máy] Thiết bị: ${objName} | Lệnh: ${cmd} | Giá trị: ${val}\n`
      code += `-- TRIGGER_DEVICE: id="${objId}", name="${objName}", command="${cmd}", value=${val}\n`
      code += `TriggerDevice("${objId}", "${objName}", "${cmd}", ${val})`
      break
    }

    case 'Comment':
      // No execution code, just represented by comment header in main loop
      break
  }
  return code
}

/**
 * Helper to extract unique used devices from workflow steps.
 */
function extractUsedDevices(steps: WorkflowStep[]): { id: string; name: string }[] {
  const map = new Map<string, string>()
  for (const s of steps) {
    if (s.type === 'TriggerDevice' && s.targetObjectName) {
      map.set(s.targetObjectId || s.targetObjectName, s.targetObjectName)
    }
  }
  return Array.from(map.entries()).map(([id, name]) => ({ id, name }))
}

/**
 * Generates Fairino robot LUA script from Workflow steps (merged single-file output).
 */
export function generateLua(
  steps: WorkflowStep[], 
  projectName: string = 'Unnamed Project',
  activeToolName: string = 'None'
): string {
  const dateStr = new Date().toISOString().split('T')[0]
  const usedDevices = extractUsedDevices(steps)
  const usedDevicesNames = usedDevices.length > 0 ? usedDevices.map(d => d.name).join(', ') : 'None'
  const usedDevicesJson = JSON.stringify(usedDevices.map(d => `${d.id}:${d.name}`))
  const luaUsedDevicesArray = usedDevices.map(d => `"${d.name}"`).join(', ')

  let lua = `-- ============================================
-- Generated by FaiRobot Studio v1.0.3
-- Project Name : ${projectName}
-- Robot Model  : Fairino FR5 (6-DOF)
-- Active Tool  : ${activeToolName}
-- Used Devices : ${usedDevicesNames}
-- DEVICE_LIST  : ${usedDevicesJson}
-- Date         : ${dateStr}
-- Note         : Compatible with Fairino Controller LUA SDK
-- ============================================

-- Active Tool & Used Devices Definitions
local ACTIVE_TOOL_NAME = "${activeToolName}"
local USED_DEVICES = {${luaUsedDevicesArray}}

-- [Utility] Safe string-to-double converter.
local function toDouble(v)
    return tonumber(tostring(v)) + 0.0
end

`

  if (steps.length === 0) {
    lua += `-- No steps recorded yet. Add waypoints in FaiRobot Studio.\n`
    return lua
  }

  const d = (n: any, decimals = 3): string => {
    const parsed = parseFloat(n)
    const val = isNaN(parsed) ? 0 : parsed
    return `toDouble("${val.toFixed(decimals)}")`
  }

  let idx = 0
  while (idx < steps.length) {
    const step = steps[idx]
    const nextStep = steps[idx + 1]

    if (step.simpleBlockRole === 'loopA' && nextStep && nextStep.simpleBlockRole === 'loopB') {
      lua += `-- [Bước ${idx + 1}] Vòng lặp: ${step.label}\n`
      if (step.comment) {
        lua += `-- Ghi chú: ${step.comment}\n`
      }

      const loopType = step.loopType || 'cycles'
      const loopValue = step.loopValue || 1

      if (loopType === 'cycles') {
        lua += `for loop_idx = 1, ${loopValue} do\n`
        lua += `    -- Đi đến B\n`
        lua += `    ${generateStepCode(nextStep, d).replace(/\n/g, '\n    ')}\n`
        lua += `    -- Đi đến A\n`
        lua += `    ${generateStepCode(step, d).replace(/\n/g, '\n    ')}\n`
        lua += `end\n\n`
      } else {
        lua += `local start_time = os.clock()\n`
        lua += `while (os.clock() - start_time < ${loopValue}) do\n`
        lua += `    -- Đi đến B\n`
        lua += `    ${generateStepCode(nextStep, d).replace(/\n/g, '\n    ')}\n`
        lua += `    -- Đi đến A\n`
        lua += `    ${generateStepCode(step, d).replace(/\n/g, '\n    ')}\n`
        lua += `end\n\n`
      }

      idx += 2
      continue
    }

    lua += `-- [Bước ${idx + 1}] ${step.label}\n`
    if (step.comment) {
      lua += `-- Ghi chú: ${step.comment}\n`
    }
    const stepCode = generateStepCode(step, d)
    if (stepCode) {
      lua += `${stepCode}\n`
    }
    lua += `\n`
    idx++
  }

  lua += `-- Kết thúc chương trình\n`
  return lua
}

/**
 * Generates Fairino robot LUA script for a single step (multi-file output).
 */
export function generateSingleStepLua(
  step: WorkflowStep,
  nextStep: WorkflowStep | null,
  projectName: string = 'Unnamed Project',
  activeToolName: string = 'None',
  stepIndex: number = 1
): string {
  const dateStr = new Date().toISOString().split('T')[0]
  const isLoop = nextStep !== null
  const usedDevices = extractUsedDevices(nextStep ? [step, nextStep] : [step])
  const usedDevicesNames = usedDevices.length > 0 ? usedDevices.map(d => d.name).join(', ') : 'None'
  const usedDevicesJson = JSON.stringify(usedDevices.map(d => `${d.id}:${d.name}`))
  const luaUsedDevicesArray = usedDevices.map(d => `"${d.name}"`).join(', ')

  let lua = `-- ============================================
-- Generated by FaiRobot Studio v1.0.3
-- Step Index   : ${stepIndex}
-- Step Type    : ${isLoop ? 'Loop Block' : step.type}
-- Project Name : ${projectName}
-- Robot Model  : Fairino FR5 (6-DOF)
-- Active Tool  : ${activeToolName}
-- Used Devices : ${usedDevicesNames}
-- DEVICE_LIST  : ${usedDevicesJson}
-- Date         : ${dateStr}
-- Note         : Compatible with Fairino Controller LUA SDK
-- ============================================

-- Active Tool & Used Devices Definitions
local ACTIVE_TOOL_NAME = "${activeToolName}"
local USED_DEVICES = {${luaUsedDevicesArray}}

-- [Utility] Safe string-to-double converter.
local function toDouble(v)
    return tonumber(tostring(v)) + 0.0
end

`

  const d = (n: any, decimals = 3): string => {
    const parsed = parseFloat(n)
    const val = isNaN(parsed) ? 0 : parsed
    return `toDouble("${val.toFixed(decimals)}")`
  }

  if (isLoop && nextStep) {
    const loopType = step.loopType || 'cycles'
    const loopValue = step.loopValue || 1

    lua += `-- Vòng lặp: ${step.label}\n`
    if (step.comment) {
      lua += `-- Ghi chú: ${step.comment}\n`
    }

    if (loopType === 'cycles') {
      lua += `for loop_idx = 1, ${loopValue} do\n`
      lua += `    -- Đi đến B\n`
      lua += `    ${generateStepCode(nextStep, d).replace(/\n/g, '\n    ')}\n`
      lua += `    -- Đi đến A\n`
      lua += `    ${generateStepCode(step, d).replace(/\n/g, '\n    ')}\n`
      lua += `end\n`
    } else {
      lua += `local start_time = os.clock()\n`
      lua += `while (os.clock() - start_time < ${loopValue}) do\n`
      lua += `    -- Đi đến B\n`
      lua += `    ${generateStepCode(nextStep, d).replace(/\n/g, '\n    ')}\n`
      lua += `    -- Đi đến A\n`
      lua += `    ${generateStepCode(step, d).replace(/\n/g, '\n    ')}\n`
      lua += `end\n`
    }
  } else {
    lua += `-- Thực thi: ${step.label}\n`
    if (step.comment) {
      lua += `-- Ghi chú: ${step.comment}\n`
    }
    const stepCode = generateStepCode(step, d)
    if (stepCode) {
      lua += `${stepCode}\n`
    }
  }

  return lua
}
