import { WorkflowStep } from '../../types/robot.types'

/**
 * Generates Fairino robot LUA script from Workflow steps.
 * Uses official Fairino LUA SDK syntax (global functions, standard parameters).
 */
export function generateLua(steps: WorkflowStep[], projectName: string = 'Unnamed Project'): string {
  const dateStr = new Date().toISOString().split('T')[0]
  
  let lua = `-- ============================================
-- Generated by FaiRobot Studio v1.0.0
-- Project Name : ${projectName}
-- Robot Model  : Fairino FR5 (6-DOF)
-- Date         : ${dateStr}
-- Note         : Compatible with Fairino Controller LUA SDK
-- ============================================

`

  if (steps.length === 0) {
    lua += `-- No steps recorded yet. Add waypoints in FaiRobot Studio.\n`
    return lua
  }

  steps.forEach((step, idx) => {
    lua += `-- [Bước ${idx + 1}] ${step.label}\n`
    
    if (step.comment) {
      lua += `-- Ghi chú: ${step.comment}\n`
    }

    switch (step.type) {
      case 'MoveJ':
        if (step.jointAngles) {
          const [j1, j2, j3, j4, j5, j6] = step.jointAngles
          // Format: MoveJ({j1, j2, j3, j4, j5, j6}, tool, user, vel, acc, blendT, blendR)
          lua += `MoveJ({${j1.toFixed(2)}, ${j2.toFixed(2)}, ${j3.toFixed(2)}, ${j4.toFixed(2)}, ${j5.toFixed(2)}, ${j6.toFixed(2)}}, 0, 0, ${step.speed.toFixed(1)}, ${step.acc.toFixed(1)}, -1.0, -1.0)\n`
        } else {
          lua += `-- Lỗi: Thiếu thông số góc khớp cho MoveJ\n`
        }
        break

      case 'MoveL':
        if (step.tcpPose) {
          const { x, y, z, rx, ry, rz } = step.tcpPose
          // Format: MoveL({x, y, z, rx, ry, rz}, tool, user, vel, acc, blendT, blendR)
          lua += `MoveL({${x.toFixed(2)}, ${y.toFixed(2)}, ${z.toFixed(2)}, ${rx.toFixed(2)}, ${ry.toFixed(2)}, ${rz.toFixed(2)}}, 0, 0, ${step.speed.toFixed(1)}, ${step.acc.toFixed(1)}, -1.0, -1.0)\n`
        } else {
          lua += `-- Lỗi: Thiếu thông số TCP cho MoveL\n`
        }
        break

      case 'RotateJoint':
        if (step.jointAngles) {
          const [j1, j2, j3, j4, j5, j6] = step.jointAngles
          lua += `MoveJ({${j1.toFixed(2)}, ${j2.toFixed(2)}, ${j3.toFixed(2)}, ${j4.toFixed(2)}, ${j5.toFixed(2)}, ${j6.toFixed(2)}}, 0, 0, ${step.speed.toFixed(1)}, ${step.acc.toFixed(1)}, -1.0, -1.0)\n`
        } else {
          lua += `-- Lỗi: Chưa giải được góc khớp cho RotateJoint\n`
        }
        break

      case 'MoveTCP':
        if (step.tcpPose) {
          const { x, y, z, rx, ry, rz } = step.tcpPose
          lua += `MoveL({${x.toFixed(2)}, ${y.toFixed(2)}, ${z.toFixed(2)}, ${rx.toFixed(2)}, ${ry.toFixed(2)}, ${rz.toFixed(2)}}, 0, 0, ${step.speed.toFixed(1)}, ${step.acc.toFixed(1)}, -1.0, -1.0)\n`
        } else {
          lua += `-- Lỗi: Chưa giải được tọa độ TCP cho MoveTCP\n`
        }
        break

      case 'SetDO':
        const doIdx = step.doIndex !== undefined ? step.doIndex : 1
        const doVal = step.doValue !== undefined ? step.doValue : 1
        const doType = step.doType || 'cabinet'
        if (doType === 'tool') {
          // Format: SetToolDO(id, status, smooth, block)
          lua += `SetToolDO(${doIdx}, ${doVal}, 0, 0)\n`
        } else {
          // Format: SetDO(index, status, block)
          lua += `SetDO(${doIdx}, ${doVal}, 0)\n`
        }
        break

      case 'WaitMs':
        const delay = step.delayMs !== undefined ? step.delayMs : 1000
        // Format: WaitMs(ms)
        lua += `WaitMs(${delay})\n`
        break

      case 'GripperOpen':
        // Map to setting DO1 to 0 (default gripper wiring setup)
        lua += `-- Điều khiển mở kẹp tay gắp\n`
        lua += `SetDO(1, 0, 0)\n`
        lua += `WaitMs(500)\n`
        break

      case 'GripperClose':
        // Map to setting DO1 to 1 (default gripper wiring setup)
        lua += `-- Điều khiển đóng kẹp tay gắp\n`
        lua += `SetDO(1, 1, 0)\n`
        lua += `WaitMs(500)\n`
        break

      case 'Comment':
        // Just comments
        break
    }
    
    lua += `\n`
  })

  lua += `-- Kết thúc chương trình\n`
  return lua
}
