import { WorkflowStep } from '../../types/robot.types'

/**
 * Generates Fairino robot LUA script from Workflow steps.
 * Uses official Fairino LUA SDK syntax (global functions, standard parameters).
 *
 * NOTE on toDouble():
 * The Fairino controller's LUA runtime may interpret bare numeric literals
 * (e.g. 90, -45) as integer rather than double. Wrapping every numeric
 * argument through the local toDouble() helper guarantees the controller
 * always receives IEEE-754 double-precision floats, avoiding type-mismatch
 * errors in MoveJ/MoveL pose parameters.
 */
export function generateLua(steps: WorkflowStep[], projectName: string = 'Unnamed Project'): string {
  const dateStr = new Date().toISOString().split('T')[0]

  let lua = `-- ============================================
-- Generated by FaiRobot Studio v1.0.0
-- Project Name : ${projectName}
-- Robot Model  : Fairino FR5 (6-DOF)
-- Date         : ${dateStr}
-- Note         : Compatible with Fairino Controller LUA SDK
-- ============================================

-- [Utility] Safe string-to-double converter.
-- The Fairino LUA runtime may parse bare integers as integer type;
-- wrapping all numeric literals through toDouble() guarantees they are
-- always treated as double-precision floats by the controller.
local function toDouble(v)
    return tonumber(tostring(v)) + 0.0
end

`

  if (steps.length === 0) {
    lua += `-- No steps recorded yet. Add waypoints in FaiRobot Studio.\n`
    return lua
  }

  const d = (n: any, decimals = 3): string => {
    const parsed = parseFloat(n)
    const val = isNaN(parsed) ? 0 : parsed
    return `toDouble("${val.toFixed(decimals)}")`
  }

  const generateStepCode = (step: WorkflowStep): string => {
    let code = ''
    switch (step.type) {
      case 'MoveJ':
        if (step.jointAngles) {
          const [j1, j2, j3, j4, j5, j6] = step.jointAngles
          // Format: MoveJ({j1..j6}, tool, user, vel, acc, blendT, blendR)
          code += `MoveJ({${d(j1)}, ${d(j2)}, ${d(j3)}, ${d(j4)}, ${d(j5)}, ${d(j6)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))`
        } else {
          code += `-- Lỗi: Thiếu thông số góc khớp cho MoveJ`
        }
        break

      case 'MoveL':
        if (step.tcpPose) {
          const { x, y, z, rx, ry, rz } = step.tcpPose
          // Format: MoveL({x, y, z, rx, ry, rz}, tool, user, vel, acc, blendT, blendR)
          code += `MoveL({${d(x)}, ${d(y)}, ${d(z)}, ${d(rx)}, ${d(ry)}, ${d(rz)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))`
        } else {
          code += `-- Lỗi: Thiếu thông số TCP cho MoveL`
        }
        break

      case 'RotateJoint':
        if (step.jointAngles) {
          const [j1, j2, j3, j4, j5, j6] = step.jointAngles
          code += `MoveJ({${d(j1)}, ${d(j2)}, ${d(j3)}, ${d(j4)}, ${d(j5)}, ${d(j6)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))`
        } else {
          code += `-- Lỗi: Chưa giải được góc khớp cho RotateJoint`
        }
        break

      case 'MoveTCP':
        if (step.tcpPose) {
          const { x, y, z, rx, ry, rz } = step.tcpPose
          code += `MoveL({${d(x)}, ${d(y)}, ${d(z)}, ${d(rx)}, ${d(ry)}, ${d(rz)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))`
        } else {
          code += `-- Lỗi: Chưa giải được tọa độ TCP cho MoveTCP`
        }
        break

      case 'SetDO': {
        const doIdx = step.doIndex !== undefined ? step.doIndex : 1
        const doVal = step.doValue !== undefined ? step.doValue : 1
        const doType = step.doType || 'cabinet'
        if (doType === 'tool') {
          // Format: SetToolDO(id, status, smooth, block)
          code += `SetToolDO(${doIdx}, ${doVal}, 0, 0)`
        } else {
          // Format: SetDO(index, status, block)
          code += `SetDO(${doIdx}, ${doVal}, 0)`
        }
        break
      }

      case 'WaitMs': {
        const delay = step.delayMs !== undefined ? step.delayMs : 1000
        // Format: WaitMs(ms)
        code += `WaitMs(${delay})`
        break
      }

      case 'GripperOpen':
        code += `-- Điều khiển mở kẹp tay gắp\n`
        code += `SetDO(1, 0, 0)\n`
        code += `WaitMs(500)`
        break

      case 'GripperClose':
        code += `-- Điều khiển đóng kẹp tay gắp\n`
        code += `SetDO(1, 1, 0)\n`
        code += `WaitMs(500)`
        break

      case 'Comment':
        // No execution code, just represented by comment header in main loop
        break
    }
    return code
  }

  let idx = 0
  while (idx < steps.length) {
    const step = steps[idx]
    const nextStep = steps[idx + 1]

    if (step.simpleBlockRole === 'loopA' && nextStep && nextStep.simpleBlockRole === 'loopB') {
      lua += `-- [Bước ${idx + 1}] Vòng lặp: ${step.label}\n`
      if (step.comment) {
        lua += `-- Ghi chú: ${step.comment}\n`
      }

      const loopType = step.loopType || 'cycles'
      const loopValue = step.loopValue || 1

      if (loopType === 'cycles') {
        lua += `for loop_idx = 1, ${loopValue} do\n`
        lua += `    -- Đi đến B\n`
        lua += `    ${generateStepCode(nextStep).replace(/\n/g, '\n    ')}\n`
        lua += `    -- Đi đến A\n`
        lua += `    ${generateStepCode(step).replace(/\n/g, '\n    ')}\n`
        lua += `end\n\n`
      } else {
        lua += `local start_time = os.clock()\n`
        lua += `while (os.clock() - start_time < ${loopValue}) do\n`
        lua += `    -- Đi đến B\n`
        lua += `    ${generateStepCode(nextStep).replace(/\n/g, '\n    ')}\n`
        lua += `    -- Đi đến A\n`
        lua += `    ${generateStepCode(step).replace(/\n/g, '\n    ')}\n`
        lua += `end\n\n`
      }

      idx += 2
      continue
    }

    lua += `-- [Bước ${idx + 1}] ${step.label}\n`
    if (step.comment) {
      lua += `-- Ghi chú: ${step.comment}\n`
    }
    const stepCode = generateStepCode(step)
    if (stepCode) {
      lua += `${stepCode}\n`
    }
    lua += `\n`
    idx++
  }

  lua += `-- Kết thúc chương trình\n`
  return lua
}
