import { WorkflowStep, JointAngles, TCPPose } from '../../types/robot.types'

/**
 * Helper to extract number from a string, handles pure float string or LUA toDouble("float_string") format.
 */
function extractNumber(str: string): number {
  const match = str.match(/toDouble\(\s*"([^"]+)"\s*\)/)
  if (match) {
    return parseFloat(match[1])
  }
  const val = parseFloat(str)
  return isNaN(val) ? 0 : val
}

/**
 * Helper to parse a single motion command (MoveJ/MoveL) from LUA code.
 */
function parseMotionCommand(line: string): Partial<WorkflowStep> | null {
  // Parse MoveJ
  const moveJMatch = line.match(/MoveJ\(\s*\{([^}]+)\}\s*,\s*[^,]+\s*,\s*[^,]+\s*,\s*([^,]+)\s*,\s*([^,]+)/)
  if (moveJMatch) {
    const joints = moveJMatch[1].split(',').map(v => extractNumber(v.trim())) as JointAngles
    const speed = extractNumber(moveJMatch[2])
    const acc = extractNumber(moveJMatch[3])
    return {
      type: 'MoveJ',
      jointAngles: joints,
      speed,
      acc,
      label: 'Di chuyển khớp (MoveJ)'
    }
  }

  // Parse MoveL
  const moveLMatch = line.match(/MoveL\(\s*\{([^}]+)\}\s*,\s*[^,]+\s*,\s*[^,]+\s*,\s*([^,]+)\s*,\s*([^,]+)/)
  if (moveLMatch) {
    const tcpVals = moveLMatch[1].split(',').map(v => extractNumber(v.trim()))
    const speed = extractNumber(moveLMatch[2])
    const acc = extractNumber(moveLMatch[3])
    const tcpPose: TCPPose = {
      x: tcpVals[0],
      y: tcpVals[1],
      z: tcpVals[2],
      rx: tcpVals[3],
      ry: tcpVals[4],
      rz: tcpVals[5]
    }
    return {
      type: 'MoveL',
      tcpPose,
      speed,
      acc,
      label: 'Di chuyển thẳng (MoveL)'
    }
  }

  return null
}

/**
 * Parses Fairino LUA script back to Workflow steps.
 * Matches code output structure generated by luaCodegen.ts.
 */
export function parseLua(luaContent: string): { steps: WorkflowStep[]; projectName?: string } {
  const steps: WorkflowStep[] = []
  let projectName = 'Imported Project'

  const lines = luaContent.split('\n')
  let currentLabel = ''
  let currentComment = ''

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim()

    // 1. Parse Project Name
    const projMatch = line.match(/-- Project Name\s*:\s*(.+)/)
    if (projMatch) {
      projectName = projMatch[1].trim()
      continue
    }

    // 2. Parse Step Metadata Comments
    const stepLabelMatch = line.match(/^--\s*\[Bước\s*\d+\]\s*(.+)/)
    if (stepLabelMatch) {
      currentLabel = stepLabelMatch[1].trim()
      currentComment = ''
      continue
    }

    const loopLabelMatch = line.match(/^--\s*Vòng lặp\s*:\s*(.+)/)
    if (loopLabelMatch) {
      currentLabel = loopLabelMatch[1].trim()
      currentComment = ''
      continue
    }

    const noteMatch = line.match(/^--\s*Ghi chú\s*:\s*(.+)/)
    if (noteMatch) {
      currentComment = noteMatch[1].trim()
      continue
    }

    // 3. Skip header comment blocks and empty lines
    if (line.startsWith('--') && !line.includes('Bước') && !line.includes('Vòng lặp') && !line.includes('Ghi chú') && !line.includes('Điều khiển') && !line.includes('Thực thi')) {
      continue
    }

    if (line === '') continue

    // Parse Loop blocks (for / while patterns)
    const forMatch = line.match(/for\s+loop_idx\s*=\s*1\s*,\s*(\d+)\s+do/)
    const whileMatch = line.match(/while\s*\(?os\.clock\(\)\s*-\s*start_time\s*<\s*(\d+)\)?\s*do/)

    if (forMatch || whileMatch) {
      const loopValue = forMatch 
        ? parseInt(forMatch[1]) 
        : parseInt(whileMatch ? whileMatch[1] : '1')
      const loopType = forMatch ? 'cycles' : 'seconds'

      // Collect all lines inside loop body until 'end'
      const loopLines: string[] = []
      let loopEndFound = false
      i++
      while (i < lines.length) {
        const subLine = lines[i].trim()
        if (subLine === 'end') {
          loopEndFound = true
          break
        }
        loopLines.push(subLine)
        i++
      }

      if (loopEndFound) {
        let loopPart: 'A' | 'B' = 'B' // B is always first in FaiRobot LUA codegen
        let stepBData: Partial<WorkflowStep> | null = null
        let stepAData: Partial<WorkflowStep> | null = null

        for (const subLine of loopLines) {
          if (subLine.includes('Đi đến B')) {
            loopPart = 'B'
            continue
          }
          if (subLine.includes('Đi đến A')) {
            loopPart = 'A'
            continue
          }

          const motion = parseMotionCommand(subLine)
          if (motion) {
            if (loopPart === 'B') {
              stepBData = motion
            } else {
              stepAData = motion
            }
          }
        }

        const baseId = `block_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`
        const stepA: WorkflowStep = {
          id: `${baseId}_loopA`,
          simpleBlockId: baseId,
          type: stepAData?.type || 'MoveJ',
          label: currentLabel || 'Điểm A (Vòng lặp)',
          comment: currentComment || undefined,
          speed: stepAData?.speed || 50,
          acc: stepAData?.acc || 50,
          jointAngles: stepAData?.jointAngles,
          tcpPose: stepAData?.tcpPose || { x: 0, y: 0, z: 0, rx: 0, ry: 0, rz: 0 },
          simpleBlockRole: 'loopA',
          loopType: loopType as 'cycles' | 'seconds',
          loopValue: loopValue
        }

        const stepB: WorkflowStep = {
          id: `${baseId}_loopB`,
          simpleBlockId: baseId,
          type: stepBData?.type || 'MoveJ',
          label: stepBData?.label || 'Điểm B (Vòng lặp)',
          speed: stepBData?.speed || 50,
          acc: stepBData?.acc || 50,
          jointAngles: stepBData?.jointAngles,
          tcpPose: stepBData?.tcpPose || { x: 0, y: 0, z: 0, rx: 0, ry: 0, rz: 0 },
          simpleBlockRole: 'loopB'
        }

        steps.push(stepA)
        steps.push(stepB)
        currentLabel = ''
        currentComment = ''
        continue
      }
    }

    // 4. Parse Gripper open/close (2-line pattern)
    // pattern:
    // SetDO(1, 0, 0)
    // WaitMs(500)
    if (line.startsWith('SetDO(1,') && i + 1 < lines.length) {
      const nextLine = lines[i + 1].trim()
      if (nextLine.startsWith('WaitMs(')) {
        const doValMatch = line.match(/SetDO\(1,\s*(\d+)/)
        const waitMatch = nextLine.match(/WaitMs\((\d+)\)/)
        if (doValMatch && waitMatch && parseInt(waitMatch[1]) === 500) {
          const val = parseInt(doValMatch[1])
          steps.push({
            id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
            type: val === 1 ? 'GripperClose' : 'GripperOpen',
            label: currentLabel || (val === 1 ? 'Đóng tay gắp' : 'Mở tay gắp'),
            comment: currentComment || undefined,
            speed: 50,
            acc: 50
          })
          currentLabel = ''
          currentComment = ''
          i++ // skip next WaitMs line
          continue
        }
      }
    }

    // 5. Parse MoveJ
    // MoveJ({j1, j2, j3, j4, j5, j6}, tool, user, vel, acc, blendT, blendR)
    const moveJMatch = line.match(/MoveJ\(\s*\{([^}]+)\}\s*,\s*[^,]+\s*,\s*[^,]+\s*,\s*([^,]+)\s*,\s*([^,]+)/)
    if (moveJMatch) {
      const joints = moveJMatch[1].split(',').map(v => extractNumber(v.trim())) as JointAngles
      const speed = extractNumber(moveJMatch[2])
      const acc = extractNumber(moveJMatch[3])
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'MoveJ',
        label: currentLabel || 'Di chuyển khớp (MoveJ)',
        comment: currentComment || undefined,
        jointAngles: joints,
        speed: speed,
        acc: acc
      })
      currentLabel = ''
      currentComment = ''
      continue
    }

    // 6. Parse MoveL
    // MoveL({x, y, z, rx, ry, rz}, tool, user, vel, acc, blendT, blendR)
    const moveLMatch = line.match(/MoveL\(\s*\{([^}]+)\}\s*,\s*[^,]+\s*,\s*[^,]+\s*,\s*([^,]+)\s*,\s*([^,]+)/)
    if (moveLMatch) {
      const tcpVals = moveLMatch[1].split(',').map(v => extractNumber(v.trim()))
      const speed = extractNumber(moveLMatch[2])
      const acc = extractNumber(moveLMatch[3])
      const tcpPose: TCPPose = {
        x: tcpVals[0],
        y: tcpVals[1],
        z: tcpVals[2],
        rx: tcpVals[3],
        ry: tcpVals[4],
        rz: tcpVals[5]
      }
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'MoveL',
        label: currentLabel || 'Di chuyển thẳng (MoveL)',
        comment: currentComment || undefined,
        tcpPose: tcpPose,
        speed: speed,
        acc: acc
      })
      currentLabel = ''
      currentComment = ''
      continue
    }

    // 7. Parse SetToolDO
    // SetToolDO(id, status, smooth, block)
    const setToolDOMatch = line.match(/SetToolDO\(\s*(\d+)\s*,\s*(\d+)/)
    if (setToolDOMatch) {
      const doIdx = parseInt(setToolDOMatch[1])
      const doVal = parseInt(setToolDOMatch[2]) as 0 | 1
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'SetDO',
        label: currentLabel || `Đặt DO Đầu gắp ${doIdx}`,
        comment: currentComment || undefined,
        doIndex: doIdx,
        doValue: doVal,
        doType: 'tool',
        speed: 50,
        acc: 50
      })
      currentLabel = ''
      currentComment = ''
      continue
    }

    // 8. Parse SetDO
    // SetDO(index, status, block)
    const setDOMatch = line.match(/SetDO\(\s*(\d+)\s*,\s*(\d+)/)
    if (setDOMatch) {
      const doIdx = parseInt(setDOMatch[1])
      const doVal = parseInt(setDOMatch[2]) as 0 | 1
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'SetDO',
        label: currentLabel || `Đặt DO Tủ điều khiển ${doIdx}`,
        comment: currentComment || undefined,
        doIndex: doIdx,
        doValue: doVal,
        doType: 'cabinet',
        speed: 50,
        acc: 50
      })
      currentLabel = ''
      currentComment = ''
      continue
    }

    // 9. Parse WaitMs
    // WaitMs(ms)
    const waitMatch = line.match(/WaitMs\(\s*(\d+)/)
    if (waitMatch) {
      const delayMs = parseInt(waitMatch[1])
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'WaitMs',
        label: currentLabel || `Chờ ${delayMs} ms`,
        comment: currentComment || undefined,
        delayMs: delayMs,
        speed: 50,
        acc: 50
      })
      currentLabel = ''
      currentComment = ''
      continue
    }
  }

  return { steps, projectName }
}
