import { WorkflowStep, JointAngles, TCPPose } from '../../types/robot.types'

/**
 * Parses Fairino LUA script back to Workflow steps.
 * Matches code output structure generated by luaCodegen.ts.
 */
export function parseLua(luaContent: string): { steps: WorkflowStep[]; projectName?: string } {
  const steps: WorkflowStep[] = []
  let projectName = 'Imported Project'

  const lines = luaContent.split('\n')
  let currentLabel = ''
  let currentComment = ''

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim()

    // 1. Parse Project Name
    const projMatch = line.match(/-- Project Name\s*:\s*(.+)/)
    if (projMatch) {
      projectName = projMatch[1].trim()
      continue
    }

    // 2. Parse Step Metadata Comments
    const stepLabelMatch = line.match(/^--\s*\[Bước\s*\d+\]\s*(.+)/)
    if (stepLabelMatch) {
      currentLabel = stepLabelMatch[1].trim()
      currentComment = ''
      continue
    }

    const noteMatch = line.match(/^--\s*Ghi chú\s*:\s*(.+)/)
    if (noteMatch) {
      currentComment = noteMatch[1].trim()
      continue
    }

    // 3. Skip header comment blocks and empty lines
    if (line.startsWith('--') && !line.includes('Bước') && !line.includes('Ghi chú') && !line.includes('Điều khiển')) {
      continue
    }

    if (line === '') continue

    // 4. Parse Gripper open/close (2-line pattern)
    // pattern:
    // SetDO(1, 0, 0)
    // WaitMs(500)
    if (line.startsWith('SetDO(1,') && i + 1 < lines.length) {
      const nextLine = lines[i + 1].trim()
      if (nextLine.startsWith('WaitMs(')) {
        const doValMatch = line.match(/SetDO\(1,\s*(\d+)/)
        const waitMatch = nextLine.match(/WaitMs\((\d+)\)/)
        if (doValMatch && waitMatch && parseInt(waitMatch[1]) === 500) {
          const val = parseInt(doValMatch[1])
          steps.push({
            id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
            type: val === 1 ? 'GripperClose' : 'GripperOpen',
            label: currentLabel || (val === 1 ? 'Đóng tay gắp' : 'Mở tay gắp'),
            comment: currentComment || undefined,
            speed: 50,
            acc: 50
          })
          currentLabel = ''
          currentComment = ''
          i++ // skip next WaitMs line
          continue
        }
      }
    }

    // 5. Parse MoveJ
    // MoveJ({j1, j2, j3, j4, j5, j6}, tool, user, vel, acc, blendT, blendR)
    const moveJMatch = line.match(/MoveJ\(\s*\{([^}]+)\}\s*,\s*[^,]+\s*,\s*[^,]+\s*,\s*([\d.]+)\s*,\s*([\d.]+)/)
    if (moveJMatch) {
      const joints = moveJMatch[1].split(',').map(v => parseFloat(v.trim())) as JointAngles
      const speed = parseFloat(moveJMatch[2])
      const acc = parseFloat(moveJMatch[3])
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'MoveJ',
        label: currentLabel || 'Di chuyển khớp (MoveJ)',
        comment: currentComment || undefined,
        jointAngles: joints,
        speed: speed,
        acc: acc
      })
      currentLabel = ''
      currentComment = ''
      continue
    }

    // 6. Parse MoveL
    // MoveL({x, y, z, rx, ry, rz}, tool, user, vel, acc, blendT, blendR)
    const moveLMatch = line.match(/MoveL\(\s*\{([^}]+)\}\s*,\s*[^,]+\s*,\s*[^,]+\s*,\s*([\d.]+)\s*,\s*([\d.]+)/)
    if (moveLMatch) {
      const tcpVals = moveLMatch[1].split(',').map(v => parseFloat(v.trim()))
      const speed = parseFloat(moveLMatch[2])
      const acc = parseFloat(moveLMatch[3])
      const tcpPose: TCPPose = {
        x: tcpVals[0],
        y: tcpVals[1],
        z: tcpVals[2],
        rx: tcpVals[3],
        ry: tcpVals[4],
        rz: tcpVals[5]
      }
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'MoveL',
        label: currentLabel || 'Di chuyển thẳng (MoveL)',
        comment: currentComment || undefined,
        tcpPose: tcpPose,
        speed: speed,
        acc: acc
      })
      currentLabel = ''
      currentComment = ''
      continue
    }

    // 7. Parse SetToolDO
    // SetToolDO(id, status, smooth, block)
    const setToolDOMatch = line.match(/SetToolDO\(\s*(\d+)\s*,\s*(\d+)/)
    if (setToolDOMatch) {
      const doIdx = parseInt(setToolDOMatch[1])
      const doVal = parseInt(setToolDOMatch[2]) as 0 | 1
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'SetDO',
        label: currentLabel || `Đặt DO Đầu gắp ${doIdx}`,
        comment: currentComment || undefined,
        doIndex: doIdx,
        doValue: doVal,
        doType: 'tool',
        speed: 50,
        acc: 50
      })
      currentLabel = ''
      currentComment = ''
      continue
    }

    // 8. Parse SetDO
    // SetDO(index, status, block)
    const setDOMatch = line.match(/SetDO\(\s*(\d+)\s*,\s*(\d+)/)
    if (setDOMatch) {
      const doIdx = parseInt(setDOMatch[1])
      const doVal = parseInt(setDOMatch[2]) as 0 | 1
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'SetDO',
        label: currentLabel || `Đặt DO Tủ điều khiển ${doIdx}`,
        comment: currentComment || undefined,
        doIndex: doIdx,
        doValue: doVal,
        doType: 'cabinet',
        speed: 50,
        acc: 50
      })
      currentLabel = ''
      currentComment = ''
      continue
    }

    // 9. Parse WaitMs
    // WaitMs(ms)
    const waitMatch = line.match(/WaitMs\(\s*(\d+)/)
    if (waitMatch) {
      const delayMs = parseInt(waitMatch[1])
      steps.push({
        id: `step_imported_${Math.random().toString(36).substring(2, 9)}_${Date.now()}`,
        type: 'WaitMs',
        label: currentLabel || `Chờ ${delayMs} ms`,
        comment: currentComment || undefined,
        delayMs: delayMs,
        speed: 50,
        acc: 50
      })
      currentLabel = ''
      currentComment = ''
      continue
    }
  }

  return { steps, projectName }
}
